//! Generates Traefik dynamic configuration (file provider) for cross-host load balancing.
//!
//! When containers are spread across multiple hosts, Traefik's Docker provider
//! only sees local containers. This module generates a YAML config file listing
//! all backends by internal_ip:host_port so Traefik can route to any host.

use std::collections::HashMap;

use crate::config::types::{Config, ServiceConfig};
use crate::docker::containers::KorgiContainer;
use crate::orchestrator::state::LiveState;

/// Path where the dynamic config is written on Traefik hosts.
pub const TRAEFIK_DYNAMIC_CONFIG_PATH: &str = "/etc/korgi/traefik-dynamic.yml";

/// Generate Traefik dynamic YAML config for all running services.
/// Maps each service to its backends across hosts using internal addresses and host ports.
pub fn generate_dynamic_config(config: &Config, state: &LiveState) -> String {
    let mut routers = Vec::new();
    let mut services = Vec::new();

    for svc_config in &config.services {
        let Some(routing) = &svc_config.routing else {
            continue; // No routing = no Traefik config (background worker)
        };
        let Some(ports) = &svc_config.ports else {
            continue; // No ports = can't route
        };

        let running = state.running_service_containers(&svc_config.name);
        if running.is_empty() {
            continue;
        }

        let router_name = format!("{}-{}", config.project.name, svc_config.name);
        let servers = build_server_list(config, svc_config, ports.host_base, &running);

        if servers.is_empty() {
            continue;
        }

        // Router
        let mut router_yaml = format!(
            "    {}:\n      rule: \"{}\"\n      service: {}",
            router_name, routing.rule, router_name,
        );

        if !routing.entrypoints.is_empty() {
            router_yaml.push_str(&format!(
                "\n      entryPoints:\n{}",
                routing
                    .entrypoints
                    .iter()
                    .map(|ep| format!("        - {}", ep))
                    .collect::<Vec<_>>()
                    .join("\n")
            ));
        }

        if routing.tls {
            router_yaml.push_str("\n      tls:\n        certResolver: letsencrypt");
        }

        routers.push(router_yaml);

        // Service with load balancer
        let mut service_yaml = format!(
            "    {}:\n      loadBalancer:\n        servers:\n{}",
            router_name,
            servers
                .iter()
                .map(|url| format!("          - url: \"{}\"", url))
                .collect::<Vec<_>>()
                .join("\n")
        );

        // Add health check if configured
        if let Some(health) = &svc_config.health {
            service_yaml.push_str(&format!(
                "\n        healthCheck:\n          path: {}\n          interval: {}\n          timeout: {}",
                health.path, health.interval, health.timeout
            ));
        }

        services.push(service_yaml);
    }

    if routers.is_empty() && services.is_empty() {
        return "# No routable services\nhttp: {}\n".to_string();
    }

    let mut yaml = "# Generated by korgi -- do not edit manually\nhttp:\n".to_string();

    if !routers.is_empty() {
        yaml.push_str("  routers:\n");
        yaml.push_str(&routers.join("\n"));
        yaml.push('\n');
    }

    if !services.is_empty() {
        yaml.push_str("  services:\n");
        yaml.push_str(&services.join("\n"));
        yaml.push('\n');
    }

    yaml
}

/// Build the list of backend server URLs for a service.
/// Each running container gets an entry: http://{internal_ip}:{host_port}
fn build_server_list(
    config: &Config,
    svc: &ServiceConfig,
    host_base: Option<u16>,
    running: &[&KorgiContainer],
) -> Vec<String> {
    let host_map: HashMap<&str, &crate::config::types::HostConfig> =
        config.hosts.iter().map(|h| (h.name.as_str(), h)).collect();

    let container_port = svc.ports.as_ref().map(|p| p.container).unwrap_or(80);

    let mut urls = Vec::new();

    for container in running {
        let Some(host_cfg) = host_map.get(container.host_name.as_str()) else {
            continue;
        };

        let internal_ip = host_cfg.internal_addr();

        // Determine the host port for this container
        let port = if let Some(base) = host_base {
            // Auto-allocated: base + instance index
            base + container.instance as u16
        } else if let Some(fixed) = svc.ports.as_ref().and_then(|p| p.host) {
            // Fixed host port (only works for 1 replica per host)
            fixed
        } else {
            // No host port config -- use container port (assumes shared network)
            container_port
        };

        urls.push(format!("http://{}:{}", internal_ip, port));
    }

    urls
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::types::*;
    use crate::docker::containers::KorgiContainer;

    fn test_config() -> Config {
        Config {
            project: ProjectConfig {
                name: "myapp".to_string(),
                secrets: None,
            },
            registries: vec![],
            hosts: vec![
                {
                    let mut h = HostConfig::test_host("web1", "203.0.113.1");
                    h.internal_address = Some("10.0.0.1".to_string());
                    h.labels = vec!["web".to_string()];
                    h
                },
                {
                    let mut h = HostConfig::test_host("web2", "203.0.113.2");
                    h.internal_address = Some("10.0.0.2".to_string());
                    h.labels = vec!["web".to_string()];
                    h
                },
            ],
            traefik: Some(TraefikConfig {
                image: "traefik:v3.2".to_string(),
                hosts: vec!["web1".to_string()],
                entrypoints: HashMap::new(),
                network: "korgi-traefik".to_string(),
                acme: None,
            }),
            services: vec![{
                let mut svc = ServiceConfig::test_service("api", "myapp/api:v1");
                svc.replicas = 3;
                svc.placement_labels = vec!["web".to_string()];
                svc.routing = Some(RoutingConfig {
                    rule: "Host(`api.example.com`)".to_string(),
                    entrypoints: vec!["websecure".to_string()],
                    tls: true,
                });
                svc.ports = Some(PortsConfig {
                    container: 8080,
                    host: None,
                    host_base: Some(9001),
                });
                svc.health = Some(HealthConfig {
                    path: "/health".to_string(),
                    interval: "10s".to_string(),
                    timeout: "3s".to_string(),
                    retries: 3,
                    start_period: None,
                });
                svc
            }],
        }
    }

    fn make_container(service: &str, generation: u64, instance: u32, host: &str) -> KorgiContainer {
        KorgiContainer {
            id: format!("{}-g{}-{}", service, generation, instance),
            name: format!("korgi-myapp-{}-g{}-{}", service, generation, instance),
            host_name: host.to_string(),
            service: service.to_string(),
            generation,
            instance,
            image: format!("myapp/{}:v1", service),
            state: "running".to_string(),
            status: "Up 5 minutes".to_string(),
            health: Some("healthy".to_string()),
        }
    }

    #[test]
    fn test_generate_dynamic_config_basic() {
        let config = test_config();
        let state = LiveState {
            containers: vec![
                make_container("api", 3, 0, "web1"),
                make_container("api", 3, 1, "web2"),
                make_container("api", 3, 2, "web1"),
            ],
        };

        let yaml = generate_dynamic_config(&config, &state);

        assert!(yaml.contains("Generated by korgi"));
        assert!(yaml.contains("myapp-api"));
        assert!(yaml.contains("Host(`api.example.com`)"));
        assert!(yaml.contains("http://10.0.0.1:9001")); // instance 0 on web1
        assert!(yaml.contains("http://10.0.0.2:9002")); // instance 1 on web2
        assert!(yaml.contains("http://10.0.0.1:9003")); // instance 2 on web1
        assert!(yaml.contains("healthCheck"));
        assert!(yaml.contains("/health"));
        assert!(yaml.contains("certResolver: letsencrypt"));
    }

    #[test]
    fn test_generate_config_uses_internal_address() {
        let config = test_config();
        let state = LiveState {
            containers: vec![make_container("api", 1, 0, "web1")],
        };

        let yaml = generate_dynamic_config(&config, &state);

        // Should use internal IP, not public
        assert!(yaml.contains("10.0.0.1"));
        assert!(!yaml.contains("203.0.113.1"));
    }

    #[test]
    fn test_generate_config_no_internal_falls_back() {
        let mut config = test_config();
        config.hosts[0].internal_address = None; // no internal address
        let state = LiveState {
            containers: vec![make_container("api", 1, 0, "web1")],
        };

        let yaml = generate_dynamic_config(&config, &state);

        // Should fall back to public address
        assert!(yaml.contains("203.0.113.1"));
    }

    #[test]
    fn test_generate_config_no_running_containers() {
        let config = test_config();
        let state = LiveState { containers: vec![] };

        let yaml = generate_dynamic_config(&config, &state);
        assert!(yaml.contains("No routable services"));
    }

    #[test]
    fn test_generate_config_worker_excluded() {
        let mut config = test_config();
        config.services.push({
            let mut svc = ServiceConfig::test_service("worker", "myapp/worker:v1");
            svc.replicas = 1;
            // No routing = not in Traefik config
            svc
        });

        let state = LiveState {
            containers: vec![
                make_container("api", 1, 0, "web1"),
                make_container("worker", 1, 0, "web1"),
            ],
        };

        let yaml = generate_dynamic_config(&config, &state);

        assert!(yaml.contains("myapp-api"));
        assert!(!yaml.contains("worker"));
    }

    #[test]
    fn test_generate_config_multiple_entrypoints() {
        let mut config = test_config();
        config.services[0].routing = Some(RoutingConfig {
            rule: "Host(`api.example.com`)".to_string(),
            entrypoints: vec!["web".to_string(), "websecure".to_string()],
            tls: false,
        });

        let state = LiveState {
            containers: vec![make_container("api", 1, 0, "web1")],
        };

        let yaml = generate_dynamic_config(&config, &state);
        assert!(yaml.contains("- web"));
        assert!(yaml.contains("- websecure"));
        assert!(!yaml.contains("certResolver")); // tls = false
    }

    #[test]
    fn test_host_port_allocation() {
        let config = test_config();
        let state = LiveState {
            containers: vec![
                make_container("api", 1, 0, "web1"), // 9001
                make_container("api", 1, 1, "web2"), // 9002
                make_container("api", 1, 2, "web1"), // 9003
                make_container("api", 1, 3, "web2"), // 9004
            ],
        };

        let yaml = generate_dynamic_config(&config, &state);
        assert!(yaml.contains(":9001"));
        assert!(yaml.contains(":9002"));
        assert!(yaml.contains(":9003"));
        assert!(yaml.contains(":9004"));
    }
}
